config/routes.rb
Rails.application.routes.draw do

  resources :searchables, path: '/search'

  resources :licenses
  resources :workhistories

  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  resources :contractors
  resources :bids

  root 'home#index'
  get '/profile', to: "home#profile"

  devise_for :users

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
  end

  resources :jobs do
    resources :bids, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :job


  def user_avatar
    self.user.contractor.avatar(:medium)
  end

  def user_avatar_small
    self.user.contractor.avatar(:thumb)
  end

  def user_url
    self.user.contractor.id
  end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  is_impressionable
  belongs_to :user

  validates_uniqueness_of :user_id

end

app/models/contractor.rb
class Contractor < ApplicationRecord
    belongs_to :user, optional: true
    has_many :workhistories, dependent: :destroy
    has_many :licenses, dependent: :destroy


    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


    def avatar_medium
      self.avatar(:medium)
    end

    def avatar_thumb
      self.avatar(:thumb)
    end

    def full_name
      "#{first_name + " " + last_name}"
    end

end

app/models/job.rb
class Job < ApplicationRecord
  is_impressionable 
  
  has_many :bids
  belongs_to :user

  before_create :localizer
  before_update :localizer



  def localizer
    self.location = "#{self.address},#{self.city},#{self.postcode}"
  end
    

  def number_of_bids
    self.bids.size
  end

  def timer
    Time.now
  end

  def impression_count
    impressions.size
  end

  def summary

    nb_words_max = 230

    if description.length > nb_words_max
      description.truncate(nb_words_max, :separator => ' ') + " ..."
    else
     self.description
    end

  end

end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :user

  has_attached_file :photowithlicense, styles: { large: "500x500", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photowithlicense, content_type: /\Aimage\/.*\z/
end

app/models/searchable.rb
class Searchable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bids, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_one :contractor, dependent: :destroy
  has_one :company, dependent: :destroy
  has_many :workhistories, dependent: :destroy
  has_many :licenses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/workhistory.rb
class Workhistory < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :contractor,  optional: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_job

  def show
  end

  def new
    @bid = Bid.new
  end

  def edit
  end

  def create
    @bid = Bid.new(bid_params)
    @bid.user_id = current_user.id
    @bid.job_id = @job.id

    if @bid.save
      redirect_to @job, notice: 'Bid was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bid.update(bid_params)
      redirect_to @job, notice: 'Bid was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bid.destroy
    redirect_to @job, notice: 'Bid was successfully destroyed.'
  end

  private

    def set_bid
      @bid = Bid.find(params[:id])
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    def bid_params
      params.require(:bid).permit(:hourly_rate, :total_rate, :note, :user_id, :job_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    if user_signed_in?
      @contractors = Contractor.where(user_id: current_user.id)
    	if @contractors.count > 0
    		redirect_to contractor_path(current_user.id)
    	else
    		render :profile
    	end

    end

    @searchable = Searchable.new

  end


  def profile
    if user_signed_in?
      @contractors = Contractor.where(user_id: current_user.id)
    	@contractors.count
    	if @contractors.count > 0
    		redirect_to contractor_path(current_user.id)
    	end
    end

  end



  private

	  def set_contractor
      
	  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @jobs = Job.all
    @bids = Bid.all

    @searchable = Searchable.new
  
  end

  def show
    @bids = Bid.where(job_id: @job.id)
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :hourly_rate, :number_of_hourse, :fixed_price, :negotiable_price, :start_hour, :end_hour, :user_id, :number_of_guards, :postcode, :address, :city )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchables_helper.rb
module SearchablesHelper
end

app/helpers/workhistories_helper.rb
module WorkhistoriesHelper
end

app/views/bids/_form.html.erb
<%= form_for([@job, @bid]) do |f| %>
  <% if bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">

  <div class="col">


    <%= f.label :note %>
    <%= f.cktext_area :note %>







  </div>


  <div class="col">

      <% if !@job.fixed_price %>

      <div class="field">
        <%= f.label :hourly_rate %><br>
        <%= f.text_field :hourly_rate, maxlength:"5", data: { 'ng-model' => 'hourlyrate' } %>
      </div>


      <div class="row">

        <div class="col">
          <label> Paid hours </label> <br>
          <h5 id="bid_number_hours">
            <%= @job.number_of_hourse %>
          </h5>
        </div>


        <div class="col">
          <label> Hourly Rate</label> <br>
          <h5 id="h5_bid_hourly_rate">
            {{hourlyrate}}
          </h5>
        </div>


        <div class="col">
          <%= f.label :total_rate %><br>
          <%= f.text_field :total_rate, class: "hidden" %>
          <h5 id="total_rate_output"></h5>
        </div>

      </div>

      <% end %>


      <div class="actions">
      <%= f.submit "Submit A Proposal", class: "btn-wide" %>
    </div>


  </div>



</div>

<% end %>

app/views/bids/edit.html.erb
<div class="container">
<h1>Editing Bid</h1>

<%= render 'form', bid: @bid %>
</div>

app/views/bids/new.html.erb
<div class="container">
  <h1>New Bid</h1>
  <%= render 'form', bid: @bid %>

</div>

app/views/bids/show.html.erb
<div class="container">

  <div class="bids_ctlr" ng-controller="bidsController">
    {{message}}
  </div>

  <div class="row">
    <div class="col">
      <strong>Note:</strong>
      <%= @bid.note.html_safe %>
    </div>

    <div class="col">
      <p>
      <strong>Hourly rate:</strong>
      <%= @bid.hourly_rate %>

      <strong>Total rate:</strong>
      <%= @bid.total_rate %>

      <%= @bid.user_avatar %>
      <br>

      <a href="<%= contractor_path (@bid.user_url) %>">
        Profile
      </a>

      <br>



      <strong>User:</strong>
      <%= @bid.user.email %>

      <strong>Job:</strong>
      <%= @bid.job.id %>
    </p>
    </div>

  </div>






  <%= link_to 'Edit', edit_job_bid_path(@bid) %> |
  <%= link_to 'Back', job_bids_path %>

</div>

app/views/jobs/_bidForm.html.erb
<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Submit a Proposal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <% if user_signed_in? %>

        <%= form_for(:bid, :url => job_bid_path(@job.id, :bid)) do |f| %>
        <div class="modal-body">


          <% if !@job.fixed_price %>

            <div class="important">
              <%= f.label :jobs_id %>
              <%= f.number_field :jobs_id, value: @job.id, type: "hidden" %>
              <%= @job.id%>
              <%= f.label :user_id %>
              <%= current_user.id%>
              <%= f.number_field :user_id, value: current_user.id, type: "hidden" %>
            </div>

            <div class="row">

              <div class="col">
                <%= f.number_field :hourly_rate, class: "form-control", placeholder: "Hourly rate", data: { 'ng-model' => 'hourlyrate' } %>
              </div>
              <div class="col">
                <%= f.number_field :total_rate, class: "form-control", placeholder: "Total rate", data: { 'ng-model' => 'total_rate' } %>
              </div>
            </div>

            <div class="row">

              <div class="col">
                <label>Hourly Rate</label>
                <h4> {{hourlyrate | currency: "£"}} </h4>
              </div>

              <div class="col">
                <label>Total Hours</label>
                <h4> {{hourlyrate | currency: "£"}} </h4>
              </div>

              <div class="col">
                <label>Total amount</label>
                <h4> {{hourlyrate | currency: "£"}} </h4>
              </div>

            </div>

            <br>

          <% end %>

          <%= f.cktext_area :note %>


        </div>
        <div class="modal-footer">
          <%= f.submit "Submit A Proposal", class: "btn-wide" %>

        </div>

        <% end %>

      <% end %>


    </div>
  </div>
</div>




<script type="text/javascript">
  $( "#bid_hourly_rate" ).change(function() {
    var noh = <%= @job.number_of_hourse %>;
    var bhr = $("#bid_hourly_rate").val();
    // var noh = $("#number_of_hourse").val();
    var btr = $("#bid_total_rate").val(noh * bhr);

    console.log(noh * bhr);

  });

</script>

app/views/jobs/_biderslist.html.erb
<ul class="biders">
  <div class="bidders_text">
      Bidders
  </div>

  <% @bids.each do |bid| %>
    <li class="bider_avatar">
      <%= image_tag bid.user_avatar %>
    </li>
  <% end %>
  <li class="bider_avatar textSpacing purple_bg">
    <%= @bids.size %>
    <% if @bids.size > 8 %>
      <%= @bids.size %>+
    <% end %>
  </li>
</ul>

<hr>

app/views/jobs/_bids.html.erb
<% if user_signed_in? %>

  <% @bids.each do |bid| %>
    <div>
      <%= bid.hourly_rate %>
      <%= bid.total_rate %>
      <%= bid.note %>
      <%= bid.user.email %>
      <%= bid.job.id %>
      <% if user_signed_in? %>
        <% if bid.user_id == current_user.id %>
          <%= link_to 'edit', edit_job_bid_path(@job,bid) %>
        <% end %>
      <% end %>
    </div>

  <% end %>

<% end %>

app/views/jobs/_form.html.erb
<%= simple_form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col">

      <div class="field">
        <%= f.text_field :title, placeholder: "Job Title" %>
      </div>

      <div class="field text_editor">

        <%= f.cktext_area :description %>

      </div>


      <div class="row the_hours">
        <div class="col">

          <div class="hour_glass">
            <%= f.label :end_hour %>

            <%= f.time_select :end_hour %>
          </div>

        </div>

        <div class="col ">
          <div class="hour_glass">
            <%= f.label :start_hour %>
            <%= f.time_select :start_hour %>
        </div>
        </div>


      </div>

      <div class="row the_dates">
        <div class="col">

          <%= f.label :start_date %>
          <%= f.text_field :start_date, class: "datepicker", placeholder: "MM / DD / YYYY" %>

        </div>

        <div class="col">

          <%= f.label :end_date %>
          <%= f.text_field :end_date, class: "datepicker", placeholder: "MM / DD / YYYY" %>
          <!-- date_select  -->
        </div>
      </div>

      <hr>

      <div class="field">
        <%= f.input :address, placeholder: "First Line of Address" %>
      </div>

      <div class="field">
        <%= f.input :city, placeholder: "City" %>
      </div>

      <div class="field">
        <%= f.input :postcode, placeholder: "Postcode" %>
      </div>


    </div>


    <div class="col">

      <div class="field">
        <%= f.label :hourly_rate %>
        <%= f.number_field :hourly_rate, placeholder: "11.50", data: { 'ng-model' => 'hourly_rate' } %>
        <p id="input_warning">Hourly rate can not be less than the national rate £7.50</p>
      </div>


      <div class="field">
        <!-- <%= f.label :number_of_hourse %> -->
        <label>Paid Hours</label>
        <%= f.number_field :number_of_hourse, placeholder: "8.59", data: { 'ng-model' => 'paid_hours'} %>
      </div>

      <div class="row">

        <div class="col">
          <div class="field">
            <%= f.label :fixed_price %>
            <%= f.check_box :fixed_price, class: "" %>
            <br>
            <label for="job_fixed_price" class="icon-toggle-on"></label>
          </div>
        </div>

        <div class="col">
          <div class="field">
            <%= f.label :negotiable_price %>
            <%= f.check_box :negotiable_price, class: "" %>
            <br>
            <label for="job_negotiable_price" class="icon-toggle-off"></label>

          </div>

        </div>

      </div>

      <div class="field">
        <%= f.input :number_of_guards, type: 'number', placeholder: "Number of guards", "ng-model":"numberofguards",  data: { 'ng-model': 'number_of_guards' } %>
        {{number_of_guards}}
      </div>




      <hr>


      <div class="hours_paid_calculation">
        <div class="calculations">

          <div>
            <label >
              <strong>Cost Per guard</strong>
            </label>
          </div>

        <div class="row">



          <div class="col">
            <label class="">Hourly rate</label> <br>
            <span id="hours_cal">{{hourly_rate | currency: "£"}}</span>
          </div>

          <div class="col">
              <label>Paid Hour's</label> <br>
              <span id="rates_cal">{{paid_hours }}</span>

          </div>

          <div class="col">
            <label >Total Amount</label> <br>
            <span id="calculations_span">{{hourly_rate * paid_hours | currency: "£"}} </span>
          </div>



        </div>


        <div class="row">
          <div class="total_cost col">
            <label>Number of grauds</label> <br>
            <span id="calculations_span">{{ number_of_guards }} </span>
          </div>

          <div class="total_cost col">
            <label>Total</label> <br>
            <span id="calculations_span">{{hourly_rate * paid_hours * number_of_guards  | currency: "£"}} </span>

            <span id="calculations_span" ng-show="hourly_rate * paid_hours < 0">
              £0.00
            </span>

          </div>

        </div>


        </div>

      </div>



      <div class="actions">
        <%= f.submit "Post Job", class: "btn-purple" %>
      </div>



    </div>

  </div>

<% end %>

app/views/jobs/_old.html.erb
<div class="wrapper_search_box wrapperTextChange">

  <div class="container">

    <div class="row">

      <div class="col full_width">
        <label class="labelSearchTags"> What</label> <br>
        <input type="search" ng-model="searchTitle.title" class="customSearchInput">
        <label class="grayLabelSmal">
          Job title, keywords or company name
        </label>
      </div>

      <div class="col full_width">
        <label class="labelSearchTags"> Where</label> <br>
        <input type="search" ng-model="searchArea.description" class="customSearchInput">
        <label class="grayLabelSmal"> City </label>
      </div>

    </div>

  </div>

</div>

<br>




<div class="jobsList hidden" ng-controller="jobsController">

  <div class="container"  ng-show='filterdShows.length > 0'>

    <div class="row">

      <div class="col">

        <div class="jobItems animated fadeInUp" ng-repeat="job in filterdShows = ( jobsList | orderBy: 'created_at':true| filter:searchTitle | filter:searchArea)" >


          <br>


          <h5 class="title">
            <a href="{{job.url}}">
              <strong>
                {{job.title}}
              </strong>
            </a>
          </h5>
          <div class="JobInfo">
            <a href="#">Company Name</a> | <span>Location {{job.postcode}}</span> | <a href="#">{{job.number_of_bids}} bids</a>  | Hourly rate : {{job.hourly_rate | currency:'£' }}
          </div>

          <p class="jobDescription">
            {{job.summary | htmlToPlaintext | limitTo:200}} ...
          </p>
          <span class="created_atJob"> {{job.created_at | date }} </span>

        </div>

      </div>


      <div class="col-4">

      </div>

    </div>



  </div>
</div>

app/views/jobs/_sidebar.html.erb
<div class="col-4">
  <div class="UserInfoShow">
    <div class="userInfoTabs">
      <label>
        <small>
          Views
        </small> <br>
        <h5>
          <%= @job.impression_count %>
        </h5>
      </label>
    </div>

    <div class="userInfoTabs">
      <label>
        <small>
          Applicants
        </small> <br>
        <h5>
          <%= @job.bids.count %>
        </h5>
      </label>
    </div>


    <div class="userInfoTabs">
      
      <label>
        <small>
          Posted
        </small> <br>
        <h5>
          <%= time_ago_in_words(@job.created_at, include_seconds: true) %>
        </h5>
      </label>


    </div>


    <div class="userInfoTabs">
      <label>
        <small>
          Start Date
        </small> <br>
        <h5>
          <%= @job.start_date %>
        </h5>
      </label>
    </div>


    <div class="userInfoTabs">
      <label>
        <small>
          End Date
        </small> <br>
        <h5>
          <%= @job.end_date %>
        </h5>
      </label>
    </div>


    <div class="userInfoTabs">
      <label>
        <small>
          Number Of Hourse
        </small> <br>
        <h5>
          <%= @job.number_of_hourse %>
        </h5>
      </label>
    </div>

    <div class="userInfoTabs">
      <label>
        <small>
          Number Of Guards
        </small> <br>
        <h5>
          <%= @job.number_of_guards %>
        </h5>
      </label>
    </div>





    <div class="userInfoTabs">
      <label>
        <small>
          Hourly Rate
        </small> <br>
        <h5>
          £ <% if @job.hourly_rate?  %>
              <%= @job.hourly_rate  %>

              <% else %>
              0.00
            
          <% end %>
          
        </h5>
      </label>
    </div>


    <div class="userInfoTabs">
      <label>
        <small>
          Fixed Price
        </small> <br>
        <h5>
          <% if @job.fixed_price? %>
              Yes
          <% else %>
              NO
          <% end %>
        </h5>
      </label>
    </div>


    <div class="userInfoTabs">
      <label>
        <small>
          Negotiable Price
        </small> <br>
        <h5>
          <% if @job.negotiable_price? %>
              Yes
          <% else %>
              No
          <% end %>
        </h5>
      </label>
    </div>


    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_job_path(@job) %> |
      <%= link_to 'Back', jobs_path %>
    <% end %>
      <%= render "jobs/bidForm" %>

      <hr class="my-4">

      <div class="text-align">
        
        <a href="<%= job_path(@job) %><%= '/bids/new'%>" class="btn-purple btn-round btn-glow btn-purple-h">
          Submit a Proposal
        </a>
      </div>




  </div>


</div>

app/views/jobs/edit.html.erb
<div class="container">

  <h4>Editing Job</h4>
  <%= render 'form', job: @job %>

</div>

app/views/jobs/index.html.erb
<br>
<br>

<div class="search_jobs">
  <div class="container">
    
    <div class="row">

      <div class="col ">
       <%= render 'searchables/searchbox' %>
      </div>

      <div class="col-md-8">
        
        <div class="jobs_items">

          <%= render 'searchables/jobitems' %>
          
        </div>

      </div>

    </div>

  </div>
</div>





<style>
  body {
    background: #f3f4f8;
  }
</style>

app/views/jobs/new.html.erb
<div class="container">

<h1>Post  Job</h1>
<%= render 'form', job: @job %>

</div>

app/views/jobs/show.html.erb
<div class="container theJob" >
  <div class="row">

    <%= render 'jobs/sidebar' %>

    <div class="col">

      <h1><%= @job.title %></h1>
      <%= render 'jobs/biderslist' %>
      <div class="jobsDescription">
        <%= @job.description.html_safe %>
      </div>
      <%= render 'jobs/bids' %>
    </div>

  </div>

</div>