config/routes.rb
Rails.application.routes.draw do

  resources :searchables, path: '/search'

  resources :licenses
  resources :workhistories

  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  resources :contractors
  resources :bids

  root 'home#index'
  get '/profile', to: "home#profile"

  devise_for :users

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
  end

  resources :jobs do
    resources :bids, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :job


  def user_avatar
    self.user.contractor.avatar(:medium)
  end

  def user_avatar_small
    self.user.contractor.avatar(:thumb)
  end

  def user_url
    self.user.contractor.id
  end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  is_impressionable
  belongs_to :user

  validates_uniqueness_of :user_id

end

app/models/contractor.rb
class Contractor < ApplicationRecord
    belongs_to :user, optional: true
    has_many :workhistories, dependent: :destroy
    has_many :licenses, dependent: :destroy


    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


    def avatar_medium
      self.avatar(:medium)
    end

    def avatar_thumb
      self.avatar(:thumb)
    end

    def full_name
      "#{first_name + " " + last_name}"
    end

end

app/models/job.rb
class Job < ApplicationRecord
  is_impressionable 
  
  has_many :bids
  belongs_to :user

  before_create :localizer
  before_update :localizer



  def localizer
    self.location = "#{self.address},#{self.city},#{self.postcode}"
  end
    

  def number_of_bids
    self.bids.size
  end

  def timer
    Time.now
  end

  def impression_count
    impressions.size
  end

  def summary

    nb_words_max = 230

    if description.length > nb_words_max
      description.truncate(nb_words_max, :separator => ' ') + " ..."
    else
     self.description
    end

  end

end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :user

  has_attached_file :photowithlicense, styles: { large: "500x500", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photowithlicense, content_type: /\Aimage\/.*\z/
end

app/models/searchable.rb
class Searchable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bids, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_one :contractor, dependent: :destroy
  has_one :company, dependent: :destroy
  has_many :workhistories, dependent: :destroy
  has_many :licenses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/workhistory.rb
class Workhistory < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :contractor,  optional: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_job

  def show
  end

  def new
    @bid = Bid.new
  end

  def edit
  end

  def create
    @bid = Bid.new(bid_params)
    @bid.user_id = current_user.id
    @bid.job_id = @job.id

    if @bid.save
      redirect_to @job, notice: 'Bid was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bid.update(bid_params)
      redirect_to @job, notice: 'Bid was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bid.destroy
    redirect_to @job, notice: 'Bid was successfully destroyed.'
  end

  private

    def set_bid
      @bid = Bid.find(params[:id])
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    def bid_params
      params.require(:bid).permit(:hourly_rate, :total_rate, :note, :user_id, :job_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    if user_signed_in?
      @contractors = Contractor.where(user_id: current_user.id)
    	if @contractors.count > 0
    		redirect_to contractor_path(current_user.id)
    	else
    		render :profile
    	end

    end

    @searchable = Searchable.new

  end


  def profile
    if user_signed_in?
      @contractors = Contractor.where(user_id: current_user.id)
    	@contractors.count
    	if @contractors.count > 0
    		redirect_to contractor_path(current_user.id)
    	end
    end

  end



  private

	  def set_contractor
      
	  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @jobs = Job.all
    @bids = Bid.all

    @searchable = Searchable.new
  
  end

  def show
    @bids = Bid.where(job_id: @job.id)
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :hourly_rate, :number_of_hourse, :fixed_price, :negotiable_price, :start_hour, :end_hour, :user_id, :number_of_guards, :postcode, :address, :city )
    end
end

app/controllers/searchables_controller.rb
class SearchablesController < ApplicationController
  before_action :set_searchable, only: [:show, :edit, :update, :destroy]

  def index
    @searchables = Searchable.all
  end

  def show
  end

  def new
    @searchable = Searchable.new
  end

  def edit
  end

  def create
    @searchable = Searchable.new(searchable_params)

    respond_to do |format|
      if @searchable.save
        format.html { redirect_to @searchable, notice: 'Searchable was successfully created.' }
        format.json { render :show, status: :created, location: @searchable }
      else
        format.html { render :new }
        format.json { render json: @searchable.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @searchable.update(searchable_params)
        format.html { redirect_to @searchable, notice: 'Searchable was successfully updated.' }
        format.json { render :show, status: :ok, location: @searchable }
      else
        format.html { render :edit }
        format.json { render json: @searchable.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @searchable.destroy
    respond_to do |format|
      format.html { redirect_to searchables_url, notice: 'Searchable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_searchable
      @searchable = Searchable.find(params[:id])
    end

    def searchable_params
      params.require(:searchable).permit(:keyword, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchables_helper.rb
module SearchablesHelper
end

app/views/searchables/_form.html.erb
<%= simple_form_for(@searchable) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :keyword %>
    <%= f.input :location %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/searchables/_jobitems.html.erb
<div class="jobs_items">
	<% @jobs.each do |job| %>
		<a href="<%= job_path(job) %>">
			<div class="job_item">
				<h3 class="title"><%= job.title %></h3>
				<label> <%= time_ago_in_words(job.created_at) %> | <%= job.city %></label>
				<div class="job_summary">
					<%= job.summary.html_safe %>
				</div>
			</div>
		</a>
	<% end %>
</div>

app/views/searchables/_searchbox.html.erb
 <div class="search_vender">
          <div class="container">
            <%= form_for (@searchable) do |f| %>
              <label>Keyword </label>
              <%= f.text_field :keyword, class: 'form-single' %>
              <br> <br>
              <label>Location </label>
              <%= f.text_field :location, class: 'form-single' %>
              <br> <br>

              <label>Jop Type</label> <br>
              <input type="text" class="form-single">
              
              <br> <br>

              <label>hourly rate </label> <br>
              <input type="text" class="form-single">

              <br> <br>

              <label>number of hourse</label> <br>
              <input type="text" class="form-single">

              <br> <br>

              <label>fixed price</label> <br>
              <input type="checkbox" class="fixed_price">

              
              


              <button class="search_btn_round">
                Search
              </button>

            <% end %>
          </div>
        </div>

app/views/searchables/edit.html.erb
<h1>Editing Searchable</h1>

<%= render 'form', searchable: @searchable %>

<%= link_to 'Show', @searchable %> |
<%= link_to 'Back', searchables_path %>

app/views/searchables/index.html.erb
<div class="container"> 
  
  <% @searchables.each do |searchable| %>
      <%= searchable.keyword %>
      <%= searchable.location %>
      <%= link_to 'Show', searchable %>
      <%= link_to 'Edit', edit_searchable_path(searchable) %>
      <%= link_to 'Destroy', searchable, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>


  <%= link_to 'New Searchable', new_searchable_path %>


</div>

app/views/searchables/new.html.erb
<h1>New Searchable</h1>

<%= render 'form', searchable: @searchable %>

<%= link_to 'Back', searchables_path %>

app/views/searchables/show.html.erb
<br>
<br>

<div class="search_jobs">
  <div class="container">
    
    <div class="row">

      <div class="col ">
      	<%= @searchable.location %>
		<%= @searchable.keyword %>
       <%= render 'searchables/searchbox' %>
      </div>

      <div class="col-md-8">
      	<%= render 'searchables/jobitems' %>
      </div>

    </div>

  </div>
</div>





<style>
  body {
    background: #f3f4f8;
  }
</style>