config/routes.rb
Rails.application.routes.draw do

  resources :searchables, path: '/search'

  resources :licenses
  resources :workhistories

  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  resources :contractors
  resources :bids

  root 'home#index'
  get '/profile', to: "home#profile"

  devise_for :users

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
  end

  resources :jobs do
    resources :bids, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :job


  def user_avatar
    self.user.contractor.avatar(:medium)
  end

  def user_avatar_small
    self.user.contractor.avatar(:thumb)
  end

  def user_url
    self.user.contractor.id
  end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
  is_impressionable
  belongs_to :user

  validates_uniqueness_of :user_id

end

app/models/contractor.rb
class Contractor < ApplicationRecord
    belongs_to :user, optional: true
    has_many :workhistories, dependent: :destroy
    has_many :licenses, dependent: :destroy


    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


    def avatar_medium
      self.avatar(:medium)
    end

    def avatar_thumb
      self.avatar(:thumb)
    end

    def full_name
      "#{first_name + " " + last_name}"
    end

end

app/models/job.rb
class Job < ApplicationRecord
  is_impressionable 
  
  has_many :bids
  belongs_to :user

  before_create :localizer
  before_update :localizer



  def localizer
    self.location = "#{self.address},#{self.city},#{self.postcode}"
  end
    

  def number_of_bids
    self.bids.size
  end

  def timer
    Time.now
  end

  def impression_count
    impressions.size
  end

  def summary

    nb_words_max = 230

    if description.length > nb_words_max
      description.truncate(nb_words_max, :separator => ' ') + " ..."
    else
     self.description
    end

  end

end

app/models/license.rb
class License < ApplicationRecord
  belongs_to :user

  has_attached_file :photowithlicense, styles: { large: "500x500", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photowithlicense, content_type: /\Aimage\/.*\z/
end

app/models/searchable.rb
class Searchable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bids, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_one :contractor, dependent: :destroy
  has_one :company, dependent: :destroy
  has_many :workhistories, dependent: :destroy
  has_many :licenses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/workhistory.rb
class Workhistory < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :contractor,  optional: true
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_job

  def show
  end

  def new
    @bid = Bid.new
  end

  def edit
  end

  def create
    @bid = Bid.new(bid_params)
    @bid.user_id = current_user.id
    @bid.job_id = @job.id

    if @bid.save
      redirect_to @job, notice: 'Bid was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bid.update(bid_params)
      redirect_to @job, notice: 'Bid was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bid.destroy
    redirect_to @job, notice: 'Bid was successfully destroyed.'
  end

  private

    def set_bid
      @bid = Bid.find(params[:id])
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    def bid_params
      params.require(:bid).permit(:hourly_rate, :total_rate, :note, :user_id, :job_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    if user_signed_in?
      @contractors = Contractor.where(user_id: current_user.id)
    	if @contractors.count > 0
    		redirect_to contractor_path(current_user.id)
    	else
    		render :profile
    	end

    end

    @searchable = Searchable.new

  end


  def profile
    if user_signed_in?
      @contractors = Contractor.where(user_id: current_user.id)
    	@contractors.count
    	if @contractors.count > 0
    		redirect_to contractor_path(current_user.id)
    	end
    end

  end



  private

	  def set_contractor
      
	  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @jobs = Job.all
    @bids = Bid.all

    @searchable = Searchable.new
  
  end

  def show
    @bids = Bid.where(job_id: @job.id)
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :hourly_rate, :number_of_hourse, :fixed_price, :negotiable_price, :start_hour, :end_hour, :user_id, :number_of_guards, :postcode, :address, :city )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchables_helper.rb
module SearchablesHelper
end

app/views/home/_footer.html.erb
<div class="footer">
  <div class="container">

    <div class="row flat">


    <ul class="col text-align-left">
      <li >© 2015 - 2017 Sebki Ltd.</li>


    </ul>

      <ul class="col text-align-right">
        <li><a href="#">About Us</a></li>
        <li><a href="#">Press</a></li>
        <li><a href="#">Careers</a></li>
        <li><a href="#">Terms of Service</a></li>
        <li><a href="#">Privacy Policy</a></li>
      </ul>

    </div>









  </div>


  <div class="text-alig-center cr-tag">
    Made With <span class="fa fa-heart color-red"></span> In London
  </div>

</div>

app/views/home/_lmtabs.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="nav-pills mb-3" id="pills-tab" role="tablist">
		  <li class="nav-item">
		    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">
		    	Who we are?
		    </a>
		  </li>
		  
		  <li class="nav-item">
		    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">
		    	What we do?
		    </a>
		  </li>
		  
		  <li class="nav-item">
		    <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">
			    Why we do it?
			</a>
		  </li>
		</ul>
	</div>

	<div class="col">
		

		<div class="tab-content" id="pills-tabContent">
			
			<div class="tab-pane card p30 fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
				We are Sebki Limited. An online based networking platform connecting members of the United Kingdom Security Industry.
			</div>

			<div class="tab-pane card p30 fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
				We hold a unique database of security personnel who are actively searching for a job. We categorise these individuals into work-related sectors based on their preferences and accreditations. 
				<br>
				<br>

				<h3>We display this</h3>
				<br>

				information in a user-friendly manner to agencies or direct employers for service users to network and
				carry out healthy business with service providers. 
				<br>
				<br>
				We also gather feedback on all security personnel and
				their service users utilising features such as bedding and ratings to encourage healthy competition
				between members and most importantly drive the industry to aspire to excellence.
			</div>

			<div class="tab-pane card p30 fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
				The security industry in the UK is largely disconnected with service provides keeping close relationships
				with allied company’s and severely distancing one another from their competitors. 
				<br>
				<br>
				We Sebki Ltd
				limited aim to bridge this gap by connecting service users to service providers and services proves to one another. 
				<br>
				<br>
				In doing so we believe we will set the pace in creating a unique online security network within the United Kingdom.

			</div>

		</div>

	</div>
</div>

app/views/home/_navbar.html.erb
<div class="navbar custom_navbar">
  <div class="container">

    <div class="row">

      <div class="col">
        <div class="branding">
          <a href="<%= root_path%>">Sebki</a>
        </div>

        <ul class="nav_links">
          <li><%= link_to "Jobs", jobs_path %></li>
          <li><%= link_to "Contractors", contractors_path %></li>
        </ul>
      </div>

      <div class="col">

        <ul class="nav_links text-right">
          <% if user_signed_in? %>
          <li>
            Hello
          </li>
          <% else %>
            <li>
              <%#= link_to'Sign In', sign_in_path  %>
              <a  data-toggle="modal" data-target="#exampleModal"> Sign in</a>
            </li>
            <li><a href="<%= new_user_registration_path %>"> Sign Up</a></li>
          <% end %>

          <% if user_signed_in? %>


          <label class="dropdown">
            <button class="profile_avatar btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="">
              <!-- Dropdown button -->
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              
              <a class="dropdown-item" href="<%= profile_path%>">
                Contractor Profile
              </a>

              <a class="dropdown-item" href="#">
            Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <hr>

              <li class="dropdown-item">
                <%= link_to'Sign Out', destroy_user_session_path, {:method => :delete}  %>
              </li>
              

            </div>
          </label>

          <% end %>
          <a href="<%= new_job_path %>">
            <button  class="btn-purple-nav">
              Post a Job
            </button>

          </a>

        </ul>

      </div>

    </div>

  </div>
</div>





<!--
<nav class="nav_bar customNavbar">

  <div class="container">

    <div class="row">

      <div class="col navbar-text">
        <a href="<%= root_path %>">
          <h2 class="navbarbrand">
            Any Guard
          </h2>
        </a>

      </div>


      <div class="col navbar-text right-text">

        <%= link_to "Jobs", jobs_path %> |
        <%= link_to "Contractors", contractors_path %> |
        <%= link_to "Post A Job", new_job_path %> |


        <% if user_signed_in? %>
          <%= link_to'Logout', destroy_user_session_path, {:method => :delete} %>
        <% else %>
          <button class="btn btn-outline-success" type="button">Main button</button>
          <%= link_to'Login', sign_in_path  %>
        <% end %>


      </div>

    </div>



    <%#= form_tag jobs_path, method: 'get' do  %>
      <%#= text_field_tag :search, params[:search] %>
    <%# end %>
  </div>

</nav> -->

app/views/home/_oldhome.html.erb
<div class="wrapper_search_box">
  <div class="container">
    <div class=" call_to_action_text">
      <h3 class="caato">
        <label class="color_red fat_text">Sebki</label>
        The smart way to hire security guards and officers.
      </h3>
    </div>

    <div class="gab"></div>

    <div class="row">

      <div class="col full_width">
        <label class="labelSearchTags"> What</label> <br>
        <input type="search" ng-model="searchTitle.title" class="customSearchInput">
        <label class="grayLabelSmal">
          Job title, keywords or company name
        </label>
      </div>

      <div class="col full_width">
        <label class="labelSearchTags"> Where</label> <br>
        <input type="search" ng-model="searchArea.description" class="customSearchInput">
        <label class="grayLabelSmal"> City </label>
      </div>

    </div>

  </div>

</div>

<div class="jobsList hidden" ng-controller="jobsController">

  <div class="container"  ng-show='filterdShows.length > 0'>

    <div class="row">

      <div class="col">

        <div class="jobItems animated fadeInUp" ng-repeat="job in filterdShows = ( jobsList | orderBy: 'created_at':true| filter:searchTitle | filter:searchArea)" >


          <br>


          <h5 class="title">
            <a href="{{job.url}}">
              <strong>
                {{job.title}}
              </strong>
            </a>
          </h5>
          <div class="JobInfo">
            <a href="#">Company Name</a> | <span>Location {{job.postcode}}</span> | <a href="#">{{job.number_of_bids}} bids</a>  | Hourly rate : {{job.hourly_rate | currency:'£' }}
          </div>

          <p class="jobDescription">
            {{job.summary | htmlToPlaintext | limitTo:200}} ...
          </p>
          <span class="created_atJob"> {{job.created_at | date }} </span>

        </div>

      </div>


      <div class="col-4">

      </div>

    </div>



  </div>
</div>


<div class="profiler_home">

  <br>
  <div class="container">
    
    <div class="row">

      <div class="col">
        <div class="card p30">
          <div class="card-body">
            <h5 class="card-title">Enhance Your Profile</h5>
            <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
            <p class="card-text">
              With a unique network of clientele be sure you will be exposed to many of the countries most exciting events and unique opportunities.
            </p>

          </div>
        </div>

      </div>



      <div class="col">
        <div class="card p30">
          <div class="card-body">
            <h5 class="card-title">Last Minute Cover</h5>
            <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
            <p class="card-text">
              With a unique pool of operatives all over the UK, we hold the perfect platform to assist you when time is running out.
            </p>

          </div>
        </div>
        
      </div>




      <div class="col">
        <div class="card p30">
          <div class="card-body">
            <h5 class="card-title">Someone Specific?</h5>
            <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
            <p class="card-text">
              For tasks that require experience and specialist skills, our platform filters down operatives and lets you

              pick the best of the best, with browsable feedback history and internal verification you can be assured you hire the right person for the job.
            </p>

          </div>
        </div>
        
      </div>


    </div>

  </div>
</div>


<div class="lmtabs">
  <div class="container">
    
    <%= render 'home/lmtabs' %>

  </div>
</div>

<!-- <div class="call_to_action">
  <div class="container">
    <h2>Hello World</h2>
  </div>
</div> -->

app/views/home/_section1.html.erb
<div class="section1" style="background-image: url('assetsandimages/bg.jpg');">

		<div class="container">
			<h3 class="calltoAction">
				<label class="fat_text">Sebki</label> <br>
		        The smart way to hire security guards and officers.
			</h3>

			<div class="search_box">
				
				<%= form_for (@searchable) do |f| %>
				    
					
				<div class="input-group">
					
					<!-- <input type="text" class="form-control form-control-lg" placeholder="What are you looking for ...."> -->
				    <%= f.text_field :keyword, class: "form-control form-control-lg", placeholder:"What are you looking for ...." %>

					<!-- <input type="text" class="form-control form-control-lg" placeholder="Location ...."> -->
					<%= f.text_field :location, class:"form-control form-control-lg", placeholder:"Location ...." %>


				  <div class="input-group-append">
				    <%= f.submit 'Search', class:"btn home_search_btn" %>
				  </div>
				</div>
	
				<% end %>

			</div>
		</div>
		
</div>

app/views/home/_section2.html.erb
	<div class="section2">

		<div class="container">

			<div class="row">
				<div class="col">


					<div class="result_items">

						<div class="result_item">
							<h5>Hotel / Residential Security / Concierge - SIA Licenced Officers</h5>

							<h6>Lodge Security Ltd | 5 applicants | <label>Posted 5 munites ago</label> </h6>

							<p>
								Valid Frontline Security Guarding or Door Supervision Licence with experience in a security or retail type role (knowledge of ASCONE is a distinct advantage)....
							</p>

						</div>


						<div class="result_item">
							<h5>Hotel / Residential Security / Concierge - SIA Licenced Officers</h5>

							<h6>Lodge Security Ltd | 5 applicants | <label>Posted 5 munites ago</label> </h6>

							<p>
								Valid Frontline Security Guarding or Door Supervision Licence with experience in a security or retail type role (knowledge of ASCONE is a distinct advantage)....
							</p>

						</div>


					</div>

				</div>
				<div class="col">
					

					<div class="result_items_slim">


						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										5 applications | 
										<label>Joined 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>


						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										Lodge Security Ltd | 5 applications | 
										<label>Posted 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>

						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										Lodge Security Ltd | 5 applications | 
										<label>Posted 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>

						<div class="result_item_slim">
							<div class="row">
								<div class="col-md-3">
									<div class="image_avatar"></div>
								</div>
								<div class="col">
									<h6>LONDON CITY SECURITY</h6>
									<h6>
										Lodge Security Ltd | 5 applications | 
										<label>Posted 5 munites ago</label>
									</h6>		
								</div>
							</div>
						</div>


					</div>

				</div>
			</div>
		</div>
	
</div>

app/views/home/_section3.html.erb
<div class="section3">

	<div class="container">
		
		<div class="row">
			<div class="col s3_items">
				<a href="#">
					<div class="item_avatar" style="background-image: url('https://images.pexels.com/photos/6224/hands-people-woman-working.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
					</div>
					<div class="info">
						<h6>Enhance Your Profile</h6>
						<p>
							With a unique network of clientele be sure you will be exposed to many of the countries most exciting events and unique opportunities.
						</p>
					</div>
				</a>
			</div>

			<div class="col s3_items">
				<a href="#">
					<div class="item_avatar" style="background-image: url('https://images.pexels.com/photos/280377/pexels-photo-280377.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');"></div>
					<div class="info">
						<h6>Last Minute Cover</h6>
						<p>
							With a unique pool of operatives all over the UK, we hold the perfect platform to assist you when time is running out...
						</p>
					</div>
				</a>
			</div>

			<div class="col s3_items">
				<a href="#">
					<div class="item_avatar" style="background-image: url('https://images.pexels.com/photos/194094/pexels-photo-194094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940');"></div>
					<div class="info">
						<h6>Someone Specific?</h6>
						<p>
							For tasks that require experience and specialist skills, our platform filters down operatives and lets you..
						</p>
					</div>
				</a>
			</div>
			
		</div>

	</div>

</div>

app/views/home/_signin.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Sign In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_for(:user, :url => session_path(:user)) do |f| %>


      <div class="modal-body">

          <div class="form-group clearfix">
            <%= f.label :email %>
            <%= f.email_field :email, placeholder: 'e.g. jon@snow.com', class: "form-control" %>
          </div>

          <div class="form-group clearfix">
            <%= f.label :password %>
            <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
          </div>

          <div class="devise-links">
            <%#= render "devise/shared/links" %>
          </div>


      </div>
      <div class="modal-footer">
        <a href="<%=  new_user_registration_path %>"class="btn btn-secondary">Sign up</a>
        <%= f.submit "Log In", class: "btn btn-default btn-orange" %>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home_page">

  <%= render 'home/section1' %>
  <%= render 'home/section2' %>
  <%= render 'home/section3' %>

</div>

app/views/home/profile.html.erb
<div class="container">

  <div class="box_center">
    
    <div class="alert alert-warning" role="alert">
      Please complete your sign up by creating a profile 
    </div>

    <div class="row">
      <div class="col">

        <div class="card p30">
          <div class="card-body">
            <h5 class="card-title">Personal Profile </h5>
            <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
            <p class="card-text">
              Creating a personal profile will give you the ability to bid on any given job. 
              <br>
              ( personal profile is suitable for security guards. please note by creating a personal profile you will not be able to post jobs )
            </p>
            <a href="<%= new_contractor_path %>" class="btn btn-round btn-purple">
              Personal Profile
            </a>

          </div>
        </div>

      </div>
      <div class="col">
        

        <div class="card p30">
          <div class="card-body">
            <h5 class="card-title">Company Profile</h5>
            <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
            <p class="card-text">
              Creating a company profile will give you the ability to post jobs
              note company profile is suitable for companies who wish to post jobs only. Companies are not allowed to bid on jobs as the biding system is strictly for individual contractors
            </p>

            <a href="<%= new_contractor_path %>" class="btn btn-round btn-purple">
              Company Profile
            </a>

          </div>
        </div>

      </div>
    </div>


    <!-- <div class="jumbotron">
      <h1 class="display-3">Hello <%#= current_user.email %></h1>
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <p class="lead">
        <a href="<%#= new_contractor_path %>" class="btn btn-round btn-purple">
          Create Profile
        </a>
      </p>
    </div> -->


  </div>

</div>