config/routes.rb
Rails.application.routes.draw do

  resources :searchables, path: '/search'

  resources :licenses
  resources :workhistories

  resources :companies
  mount Ckeditor::Engine => '/ckeditor'
  resources :contractors
  resources :bids

  root 'home#index'
  get '/profile', to: "home#profile"

  devise_for :users

  devise_scope :user do
    get '/sign_in', to: 'devise/sessions#new'
    get '/sign_up', to: 'devise/registrations#new'
  end

  resources :jobs do
    resources :bids, except: [:index]
  end

end

app/models/contractor.rb
class Contractor < ApplicationRecord
    belongs_to :user, optional: true
    has_many :workhistories, dependent: :destroy
    has_many :licenses, dependent: :destroy


    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


    def avatar_medium
      self.avatar(:medium)
    end

    def avatar_thumb
      self.avatar(:thumb)
    end

    def full_name
      "#{first_name + " " + last_name}"
    end

end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]


  def index
    @contractors = Contractor.all
  end

  def show
    @work = Workhistory.new
    @lcq = License.new

    @lcq.contractor_id = @contractor.id

    @lcqs = License.where(user_id: @contractor.user_id).order("created_at DESC")


    @workhistories = Workhistory.where(contractor_id: @contractor.id)
    @license = License.new
    @licenses = License.where(contractor_id: @contractor.id)

    @mertic_apps = "0" 
    @bids = Bid.where(user_id: @contractor.contracts_id)

  end

  def new
    @contractor = Contractor.new
    @contractor.user_id = current_user.id
  end

  def edit
  end

  def create
    @contractor = Contractor.new(contractor_params)
    @contractor.contracts_id = current_user.id

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: 'Contractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    def contractor_params
      params.require(:contractor).permit(:first_name, :last_name, :avatar, :gender, :dob, :firstline_address, :postcode, :city, :county, :country, :mobile, :utr, :contracts_id, :right_to_work_uk, :bio, :user_id, :preferred_hourly_rate)
    end
end

app/helpers/contractors_helper.rb
module ContractorsHelper

end

app/views/contractors/_certification_tab.html.erb
<div class="tab-pane fade" id="certification" role="tabpanel" aria-labelledby="certification-tab">
  

<div class="conatiner">
    <div class="ProfileBio">

	<% if user_signed_in? %>
          <div class="jumbotron">

          	
            

            <div class="row">
          		<div class="col">

          			<h4 class="">License</h4>
          			<p class="lead">
		              <% if @workhistories.exists? %>
		                Use the button below to add a License.
		              <% else %>
		                you don't have any License or Certifications at the moment, <br>
		                please click the button below to add a work history.
		              <% end %>

		            </p>
		            <p class="lead">
		              <button class="btn btn-round btn-purple" data-toggle="modal" data-target="#lcmodel">
		              	<i class="fa fa-plus" aria-hidden="true"></i>
		              	New
					  </button>

		            </p>
          			
          		</div>
          		<div class="col">
          			
					<h4 class="">Certifications</h4>
          			<p class="lead">
		              <% if @workhistories.exists? %>
		                Use the button below to add a Certification.
		              <% else %>
		                you don't have a Certification at the moment, <br>
		                please click the button below to add a Certification.
		              <% end %>

		            </p>
		            <p class="lead">
		              <button class="btn btn-round btn-purple" data-toggle="modal" data-target="#lcmodel">
		              	<i class="fa fa-plus" aria-hidden="true"></i>
		              	New
					  </button>

		            </p>


          		</div>
          	</div>
            
          </div>
    <% end %>
	</div>
</div>



<div class="row">
	<div class="col">
		<h5>LICENCE</h5>
		<% @lcqs.each do |l|%>
			<div class="cards_mist">
				<h5><%= l.ltype %></h5>
				<p>
					Expiration date: <strong>
						<%= l.exdate %>
					</strong> <br>
				</p>
			</div>
		<% end %>

	</div>

	<div class="col">
		<h5>CERIFICATIONS</h5>
		<div class="cards_mist">
			<h5>hello</h5>
			<p>
				you don't have a Certification at
			</p>
		</div>
	</div>
</div>
  

  <div class="modal fade" id="lcmodel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">

	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLabel">
		        ADD LICENSE
		    </h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>

	      <%= simple_form_for(@lcq) do |f| %>
			<div class="modal-body">

				<div class="field">
					<%= f.file_field :photowithlicense %>					
				</div>
				
				<div class="field ltype_cover">
					<%= f.select :ltype,
					[
						'Cash and Valuable in Transit',
						'Close Protection',
						'Key holder',
						'Security Guarding'] , class: 'form-control'
					%>
				</div>

				<div class="field">
					<%= f.label :lNumbe, 'Licence Number'%>
					<%= f.text_field :lNumbe, class: 'form-control', placeholder: "LICENCE NUMBER" %>
				</div>

				<div class="field">
					<%= f.text_field :exdate, class: 'form-control datepicker', placeholder: "MM/DD/YYYY" %>
				</div>


			</div>

			<div class="modal-footer">
				<%= f.submit 'Save changes', class: "btn btn-round btn-purple" %>
			</div>

		  <% end %>


	    </div>

	  </div>
	</div>

</div>

app/views/contractors/_details.html.erb
<div class="UserInfoShow">

  <div class="userInfoTabs" >
    <label>
      <small>
        Last Name
      </small> <br>
      <h5>
        <%= @contractor.first_name + " " + @contractor.last_name %>
      </h5>
    </label>
  </div>

  <div class="userInfoTabs" >
    <label>
      <small>
        Gender
      </small> <br>
      <h5>
        <%= @contractor.gender %>
      </h5>
    </label>
  </div>

  <div class="userInfoTabs" >
    <label>
      <small>
        City
      </small> <br>
      <h5>
        <%= @contractor.city %>
      </h5>
    </label>
  </div>

  <%= render 'contractors/services_tab' %>

</div>

app/views/contractors/_form.html.erb
<%= form_for(contractor) do |f| %>
  <% if contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
      <% contractor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="row" ng-controller="contractorsController">
    <div class="col">

      <div class="field">
        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
      </div>

      <div class="field">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>


      <div class="field">
        <%= f.label :gender %>
        <%= f.text_field :gender %>
      </div>

      <div class="field">
        <%= f.label :dob %>
        <%= f.text_field :dob, class: "datepicker" %>
      </div>

      <div class="field">
        <%= f.label :firstline_address %>
        <%= f.text_field :firstline_address %>
      </div>

      <div class="field">
        <%= f.label :postcode %>
        <%= f.text_field :postcode, class: "target" %>
        <p>
          <i class="fa fa-times" aria-hidden="true"></i> please enter a valid postcode
        </p>
      </div>

      <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>

      <div class="field">
        <%= f.label :county %>
        <%= f.text_field :county %>
      </div>

      <div class="field">
        <%= f.label :country %>
        <%= f.text_field :country %>
      </div>
    </div>


    <div class="col">
      <div class="field">
        <%= f.label :mobile %>
        <%= f.number_field :mobile %>
      </div>

      <div class="field">
        <%= f.label :utr %>
        <%= f.text_field :utr %>
      </div>

      <div class="field">
        <%= f.label :contracts_id %>
        <%= f.text_field :contracts_id %>
      </div>

      <div class="field">
        <%= f.label :right_to_work_uk %>
        <%= f.check_box :right_to_work_uk %>
      </div>

      <div class="field">
        <%= f.label :preferred_hourly_rate %>
        <%= f.number_field :preferred_hourly_rate %>
      </div>

      <div class="field">
        <label> Cover Letter (Optional)</label>
        <%= f.cktext_area :bio %>

      </div>


      <div class="actions">
        <%= f.submit "Create Profile" ,class: "btn-purple" %>
      </div>


    </div>


  </div>








<% end %>

app/views/contractors/_metrics.html.erb
<div class="metrics">

  <div class="container">

    <div class="row">

      <div class="col-3">

        <div class="MetricsAvatr">
          <div class="theAvatarImage">
            <%= image_tag @contractor.avatar_medium %>
          </div>
        </div>

      </div>

      <div class="col">

        <div class="UserInfo">
          <%= @contractor.first_name + " " + @contractor.last_name  %>
          <%= @all %>
          <small>
          </small>
          <% if user_signed_in? %>
            <% if current_user.id == @contractor.user_id %>
              <a href="<%= edit_contractor_path(@contractor) %>">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              </a>
            <% end %>
          <% end %>

          <br>
          <p id="metCity">
            <span class="badge badge-danger">Pending Verification</span> |
            <i class="fa fa-shield" aria-hidden="true"></i> SIA  |
          <i class="fa fa-map-marker" aria-hidden="true"></i> <%= @contractor.city %> </p>

          <br>

          <div class="row">

            <div class="col">
              <span id="metCity">Total</span>
              <br>0
            </div>

            <div class="col">
              <span id="metCity">Applications</span>  

                <br><%= @bids.count %>
            </div>

            <div class="col">
              <span id="metCity">Hired</span>
              <br>0
            </div>

          </div>

        </div>

      </div>

    </div>



  </div>

  <div class="metNav">

    <div class="container">

      <div class="row">

        <div class="col">

          <ul class="removeLinkStyles">
            <a id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-expanded="true" class="active">
              <li> Overview</li>
            </a>
            <a  id="workHistory-tab" data-toggle="tab" href="#workHistory" role="tab" aria-controls="workHistory" aria-expanded="true">
              <li> Work History</li>
            </a>
            <a id="certification-tab" data-toggle="tab" href="#certification" role="tab" aria-controls="certification" aria-expanded="true">
              <li> license & certifications</li>
            </a>

          </ul>

        </div>

      </div>



    </div>
  </div>

</div>

app/views/contractors/_overview_tab.html.erb
<div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
    <div class="conatiner">

    <div class="ProfileBio">
      <label>
        <small>
          <strong>
            Personal Bio
          </strong>
        </small>
      </label>
      <%= @contractor.bio.html_safe %>
    </div>

  </div>

</div>

app/views/contractors/_relatedContractors.html.erb
<div class="RecomedationContractors" ng-controller="contractorsController">
  <label id="titleRec">Other Contractors in the area</label>
  <div class="GuardsProfiles">

    <ul class="biders" ng-repeat="bid contractors">
      <li ng-repeat="bid in job.bids | limitTo:4" class="result_avatar">
        <img ng-src="{{bid.user_avatar}}" alt="">
      </li>
      <li class="result_avatar resultTextSpacing purple_bg">
        {{job.bid_size}}
      </li>
    </ul>


  </div>
</div>

app/views/contractors/_services_tab.html.erb
<div class="userInfoTabs" >
  <label>
    <small>
      Services
    </small> <br>
    <span class="badge badge-dark">
      <i class="fa fa-paw" aria-hidden="true"></i> Dog Handler
    </span>
    <span class="badge badge-dark">
      <i class="fa fa-key" aria-hidden="true"></i>
      Key Holder
    </span>
  </label>
</div>


<div class="userInfoTabs" >
  <label>
    <small>
      Sectors
    </small> <br>
    <span class="badge badge-primary">
      Constraction
    </span>
    <span class="badge badge-primary">
      Corperate
    </span>
  </label>
</div>

app/views/contractors/_tabs.html.erb
<div class="tab-content" id="myTabContent">
  <%= render 'contractors/overview_tab' %>
  <%= render 'contractors/workhistory_tab' %>
  <%= render 'contractors/certification_tab' %>
</div>

app/views/contractors/_workhistory_tab.html.erb
<div class="tab-pane fade" id="workHistory" role="tabpanel" aria-labelledby="workhistory-tab">
  <div class="conatiner">
    <div class="ProfileBio">

      <% if user_signed_in? %>
          <div class="jumbotron">
            <h4 class="">Work History</h4>
            <p class="lead">
              <% if @workhistories.exists? %>
                Use the button below to add more work history.
              <% else %>
                you don't have a work history at the moment, <br>
                please click the button below to add a work history.
              <% end %>

            </p>
            <p class="lead">
              <button type="button" class="btn btn-round btn-purple" id="toggleWorkHistory">
                <i class="fa fa-plus" aria-hidden="true"></i>
                New
              </button>
            </p>
          </div>
      <% end %>




      <% if @workhistories.exists? %>


      <table class="table table-hover">
        <thead>
          <tr>
            <th>Comapny</th>
            <th>Role</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
        </thead>
        <tbody>
          <% @workhistories.each do |work| %>
          <tr data-toggle="modal" data-target="#exampleModalLong<%= work.id %>">
            <td><%= work.company_name %></td>
            <td><%= work.your_role %></td>
            <td><%= work.start_date %></td>
            <td><%= work.end_date %></td>
          </tr>

          <!-- Modal -->

          <div class="modal fade" id="exampleModalLong<%= work.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle<%= work.id %>" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle"><%= work.company_name %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= work.note %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
              </div>
            </div>
          </div>

          <% end %>

        </tbody>
      </table>


      <% else %>
        <h2>NO</h2>
      <% end %>



    </div>
  </div>
</div>


<div class="fullcoverModel hidden animated fadeIn" id="fullcoverModel">

<aside class="sideForum">
  <div class="form-group">
    <h2>Work History</h2>
    <%#= form_for(:workhistory, :url => workhistory_path) do |f| %>
    <%= simple_form_for(@work) do |f| %>
      <%= f.hidden_field :contractor_id, :value => @contractor.id %>
      <div class="field">
        <%= f.text_field :company_name, class: "form-control", placeholder: "Company name" %>
      </div>
      <div class="field">
        <%= f.text_field :your_role, class: "form-control", placeholder: "Your Role"  %>
      </div>
      <div class="row">
        <div class="col">
          <%= f.text_field :start_date, class: "form-control datepicker", placeholder: "MM/DD/YYYY"  %>
        </div>
        <div class="col">
          <%= f.text_field :end_date, class: "form-control datepicker", placeholder: "MM/DD/YYYY" %>
        </div>
      </div>
      <br>
      <%= f.text_area :note, class: "form-control" %>
      <%= f.submit " Add Work History ", class: "btn btn-round btn-purple btn-glow-purple" %>
      <button type="button" class="btn btn-round btn-white" id="toggleWorkHistoryTwo" >
        Cancel
      </button>

    <% end %>

  </div>
</aside>


</div>

app/views/contractors/edit.html.erb
<div class="container">

  <h1>Editing Contractor</h1>
  <%= render 'form', contractor: @contractor %>
  <%= link_to 'Show', @contractor %> |
  <%= link_to 'Back', contractors_path %>

</div>

app/views/contractors/index.html.erb
<div class="wrapper_search_box wrapperTextChange">

  <div class="container">
    <div class="row">
      <div class="col full_width">
        <label class="labelSearchTags"> Who</label> <br>
        <input type="search" ng-model="searchContractor.first_name" class="customSearchInput ng-pristine ng-untouched ng-valid ng-empty">
        <label class="grayLabelSmal">
          Full Name
        </label>
      </div>

      <div class="col full_width">
        <label class="labelSearchTags"> Where</label> <br>
        <input type="search" ng-model="searchContractor.city" class="customSearchInput ng-pristine ng-untouched ng-valid ng-empty">
        <label class="grayLabelSmal"> City </label>
      </div>
    </div>
  </div>

</div>

<div class="container" ng-controller="contractorsController">

  <div class="contractorItems">

    <div class="fillters">
      <!-- filters -->
    </div>


    <div class="row">


      <div class="col">

        <div class="profileItemsList animated fadeIn" ng-animate="animate" ng-repeat="person in filterdShows = ( contractors | orderBy: 'created_at':true| filter:searchContractor.first_name | filter:searchContractor.city)" >

          <div class="itemTop">

            <div class="row">
              <div class="col text-left">
                <span ng-if="person.right_to_work_uk == true">
                  <span class="badge badge-success">Verified</span>
                </span>

                <span ng-if="person.right_to_work_uk == false">
                  <span class="badge badge-warning">Pending</span>
                </span>

              </div>

              <div class="col text-right">
                <strong>{{person.preferred_hourly_rate | currency:"£"}}/hr</strong>
              </div>
            </div>


          </div>
          <div class="itemCenter">

            <div class="cover_avatar">
              <img ng-src="{{person.avatar_medium}}" alt="">
            </div>
            <h5 class="personName">  {{person.full_name}} </h5>
            <p class="personCity">{{person.city}}</p>
          </div>
          <div class="itemBottom">
            <hr>
            <a href="{{person.url}}">
              <button type="button" class="btn-full-purple" >
                VIEW PROFILE
              </button>
             </a>
          </div>

        </div>


      </div>

    </div>


  </div>

  <!-- End angular  -->
  <hr>

    <%= link_to 'New Contractor', new_contractor_path %>



</div>

app/views/contractors/new.html.erb
<div class="container">
    <h1>New Contractor</h1>
    <%= render 'form', contractor: @contractor %>
</div>

app/views/contractors/show.html.erb
<%= render 'contractors/metrics'%>
<div class="container">

  <div class="row">

    <div class="col-3">
      <%= render 'contractors/details' %>
    </div>


      <div class="col">

        <%= render 'tabs' %>

      </div>

  </div>


</div>